Trabajo Tarea 4 Clase 5
sergio-ceballos-intelex/tareas-modulo-3-grupo-6 pull request #30
Opened 2024-04-19 01:39 UTC by joc-dog

Profe para su revision.

Sinceramente copie la parte del script de la funcion isprimo de esta pagina https://medium.com/@holasoymalva/como-saber-si-un-n%C3%BAmero-es-primo-o-no-en-javascript-2edb798526d4#:~:text=En%20JavaScript%2C%20podemos%20determinar%20si,entonces%20el%20n%C3%BAmero%20es%20primo.

El resto si trate de meter lo visto en las clases anteriores.

Ando un poco perdido en el tema visto en la ultima clase.

2024-04-19 18:01 UTC, sergio-ceballos-intelex commented on jose_polanco_16929837/Tarea-4-Clase-5/js/main-fruteria.js
> +    }else if(kiloWeight > 10){
aqui sobra el else if, puedes dejarle como un else nada mas

2024-04-20 00:14 UTC, joc-dog commented on jose_polanco_16929837/Tarea-4-Clase-5/js/main-fruteria.js
> +    }else if(kiloWeight > 10){
Enterado.

2024-04-20 22:10 UTC, sergio-ceballos-intelex commented on jose_polanco_16929837/Tarea-4-Clase-5/js/main-fruteria.js
> +    }else(kiloWeight > 10){
ahi no hace falta la condicion, es decir deja solo el asi: else { ... }

2024-04-25 17:53 UTC, sergio-ceballos-intelex requested changes
jose por fa haz la modificacion que te pedi en esta rama para fusionar la tarea con main

2024-04-28 02:04 UTC, merged